apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/version: 3.3.1
    control-plane: elastic-operator
  name: elastic-operator
  namespace: elastic-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      annotations:
        checksum/config: c85f7755c815e13d98938c3c7d15c640dd2b5636a8dc80874f9f88c6cbd7a3ee
        co.elastic.logs/raw: '[{"type":"filestream","enabled":true,"id":"eck-container-logs-${data.kubernetes.container.id}","paths":["/var/log/containers/*${data.kubernetes.container.id}.log"],"parsers":[{"container":{}},{"ndjson":{"keys_under_root":true}}],"prospector.scanner.symlinks":true,"processors":[{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"error","to":"_error"}]}},{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"_error","to":"error.message"}]}},{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"source","to":"_source"}]}},{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"_source","to":"event.source"}]}}]}]'
      labels:
        control-plane: elastic-operator
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - manager
        - --config=/conf/eck.yaml
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: WEBHOOK_SECRET
          value: elastic-webhook-server-cert
        image: docker.elastic.co/eck/eck-operator:3.3.1
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 9443
          name: https-webhook
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /conf
          name: conf
          readOnly: true
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: elastic-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: elastic-operator
        name: conf
      - name: cert
        secret:
          defaultMode: 420
          secretName: elastic-webhook-server-cert
