apiVersion: v1
data:
  oidc.clientSecret: YXJnb3NlY3JldDwvIUNoYW5nZU1FIVw+
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
