apiVersion: v1
data:
  plugin.yaml: "apiVersion: argoproj.io/v1alpha1\nkind: ConfigManagementPlugin\nmetadata:\n
    \ name: sops-kustomize\nspec:\n  version: v1.0\n  init:\n    command: [\"sh\",
    \"-c\"]\n    args:\n      - 'find . -type f -name \"*.yaml\" -exec grep -l \"sops:\"
    {} + | xargs -r -n 1 sops -d -i' \n  generate:\n    command:\n      - \"kustomize\"\n
    \   args:\n      - \"build\"\n      - \"--enable-helm\"\n      - \".\"\n"
kind: ConfigMap
metadata:
  name: argocd-sops-plugin
  namespace: argocd
