apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: ZHVtbXkta2V5
  AWS_REGION: dXMtZWFzdC0x
  AWS_SECRET_ACCESS_KEY: ZHVtbXktc2VjcmV0
kind: Secret
metadata:
  name: aws-kms-credentials
  namespace: argocd
type: Opaque
