deployment:
  envoyGateway:
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 300m
        memory: 256Mi

  ports:
    - name: metrics
      port: 19001
      targetPort: 19001
  pod:
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '19001'

metrics:
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: "envoy-gateway-system"

config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    provider:
      type: Kubernetes
    
    admin:
      address:
        host: "0.0.0.0"
        port: 19000
      enableDumpConfig: true
      enablePprof: true

    logging:
      level:
        default: info

    # Control Plane Telemetry
    telemetry:
      metrics:
        prometheus:
          disable: false

    # Enable advanced/experimental routing features
    extensionApis:
      enableBackend: true          # Enables routing to Unix Sockets & external FQDNs
      enableEnvoyPatchPolicy: true # Enables raw xDS Envoy config patching (for edge-cases)
      disableLua: false            # Ensures Lua scripting is available on the gateway

    envoyProxy:
      telemetry:
        metrics:
          prometheus:
            disable: false
        accessLog:
          settings:
            # Rich Nginx-like access logging + Envoy upstream durations
            - format:
                type: Text
                text: '[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"\n'

topologyInjector:
  enabled: true
