apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: sops-kustomize
spec:
  version: v1.0
  init:
    command: ["sh", "-c"]
    args:
      - 'find . -type f -name "*.yaml" -exec grep -l "sops:" {} + | xargs -r -n 1 sops -d -i' 
  generate:
    command:
      - "kustomize"
    args:
      - "build"
      - "--enable-helm"
      - "."
