apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: sops-kustomize
spec:
  version: v1.0
  init:
    command: ["sh", "-c"]
    args:
      - |
        echo "Decrypting SOPS files..."        
        find . -type f -name "*.yaml" -exec sh -c 'grep -q "sops:" "$1" && sops -d -i "$1" || true' _ {} \;
  generate:
    command:
      - "kustomize"
    args:
      - "build"
      - "--enable-helm"
      - "."
